services:
  backend:
    build: .
    ports:
      - "8036:8036"
    environment:
      - CONNECTION_DB=mongodb://admincvm:JDDok45h674830hfusORtwWW4fdf65B@mongo:27017/cvmdbs?authSource=admin
      - SPRING_DATA_MONGODB_URI=mongodb://admincvm:JDDok45h674830hfusORtwWW4fdf65B@mongo:27017/cvmdbs?authSource=admin
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - cvm-network

  mongo:
    image: mongo:latest
    container_name: mongopos
    ports:
      # Puerto abierto al público para que te conectes desde MongoDB Compass externa
      - "12876:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admincvm
      - MONGO_INITDB_ROOT_PASSWORD=JDDok45h674830hfusORtwWW4fdf65B
      - TZ=America/Caracas
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - cvm-network
    # El healthcheck corregido con los parámetros oficiales de autenticacion de mongosh
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')", "-u", "admincvm", "-p", "JDDok45h674830hfusORtwWW4fdf65B", "--authenticationDatabase", "admin"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo-data:
  mongo-config:

networks:
  cvm-network:
    driver: bridge