spring.application.name=cvm
server.port=${PORT:8036}
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/cvmdbs}

# ===================================================================
# CONFIGURACIÓN DE LOGS (OPCIONAL PARA DEBUG)
# ===================================================================
# logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
