spring.application.name=cvm
server.port=${PORT:8080}


# Formato: mongodb://[usuario:contraseña@]host[:puerto]/base_de_datos
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/cvm_test}

# ===================================================================
# CONFIGURACIÓN DE LOGS (OPCIONAL PARA DEBUG)
# ===================================================================
# logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
